// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFrete.Migrations;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFrete.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831153501_TripsAndMatching")]
    partial class TripsAndMatching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFrete.BuildingBlocks.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("AggregateType", "AggregateId")
                        .HasDatabaseName("ix_audit_event_aggregate_type_aggregate_id");

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("MyFrete.BuildingBlocks.Configuration.ConfigurationEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_configuration");

                    b.ToTable("configuration", (string)null);
                });

            modelBuilder.Entity("MyFrete.BuildingBlocks.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("response_content_type");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_key");

                    b.ToTable("idempotency_key", (string)null);
                });

            modelBuilder.Entity("MyFrete.BuildingBlocks.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_dedupe_key")
                        .HasFilter("dedupe_key IS NOT NULL");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_state_next_attempt_at");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("MyFrete.Modules.Accounts.Domain.ClientProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserId")
                        .HasName("pk_client_profile");

                    b.ToTable("client_profile", "accounts");
                });

            modelBuilder.Entity("MyFrete.Modules.Accounts.Domain.DataSubjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_data_subject_request");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_data_subject_request_user_id_status");

                    b.ToTable("data_subject_request", "accounts");
                });

            modelBuilder.Entity("MyFrete.Modules.Accounts.Domain.ProfessionalProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ImmediateAvailability")
                        .HasColumnType("boolean")
                        .HasColumnName("immediate_availability");

                    b.Property<Point>("LastLocation")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("last_location");

                    b.Property<DateTimeOffset?>("LastLocationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_location_at");

                    b.Property<int>("MaxLoadGrams")
                        .HasColumnType("integer")
                        .HasColumnName("max_load_grams");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("verification_status");

                    b.HasKey("UserId")
                        .HasName("pk_professional_profile");

                    b.HasIndex("ImmediateAvailability")
                        .HasDatabaseName("ix_professional_profile_immediate_availability")
                        .HasFilter("immediate_availability");

                    b.HasIndex("LastLocation")
                        .HasDatabaseName("ix_professional_profile_last_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastLocation"), "gist");

                    b.ToTable("professional_profile", "accounts");
                });

            modelBuilder.Entity("MyFrete.Modules.Accounts.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", "accounts");
                });

            modelBuilder.Entity("MyFrete.Modules.Accounts.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_access_count");

                    b.Property<DateTimeOffset?>("LockoutEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", "accounts");
                });

            modelBuilder.Entity("MyFrete.Modules.Accounts.Domain.VerificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_verification_event");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_verification_event_professional_id");

                    b.ToTable("verification_event", "accounts");
                });

            modelBuilder.Entity("MyFrete.Modules.Matching.Domain.MatchingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("ContactedCount")
                        .HasColumnType("integer")
                        .HasColumnName("contacted_count");

                    b.Property<string>("ContactedIdsCsv")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("contacted_ids");

                    b.Property<Guid?>("CurrentOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_offer_id");

                    b.Property<DateTimeOffset>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<double>("OriginLat")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_lat");

                    b.Property<double>("OriginLng")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_lng");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<int>("WeightGrams")
                        .HasColumnType("integer")
                        .HasColumnName("weight_grams");

                    b.HasKey("Id")
                        .HasName("pk_matching_session");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_matching_session_request_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_matching_session_state");

                    b.ToTable("matching_session", "matching");
                });

            modelBuilder.Entity("MyFrete.Modules.Matching.Domain.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("RespondBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respond_by");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_offer");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_offer_session_id");

                    b.HasIndex("ProfessionalId", "Outcome")
                        .HasDatabaseName("ix_offer_professional_id_outcome");

                    b.ToTable("offer", "matching");
                });

            modelBuilder.Entity("MyFrete.Modules.Notifications.Domain.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_device_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_token_user_id");

                    b.ToTable("device_token", "notifications");
                });

            modelBuilder.Entity("MyFrete.Modules.Notifications.Domain.NotificationDispatch", b =>
                {
                    b.Property<string>("DedupeKey")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("dedupe_key");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("DedupeKey")
                        .HasName("pk_notification_dispatch");

                    b.ToTable("notification_dispatch", "notifications");
                });

            modelBuilder.Entity("MyFrete.Modules.Pricing.Domain.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_fare");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_price");

                    b.Property<decimal>("PerKg")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("per_kg");

                    b.Property<decimal>("PerKm")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("per_km");

                    b.HasKey("Id")
                        .HasName("pk_pricing_rule");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("ix_pricing_rule_effective_from");

                    b.ToTable("pricing_rule", "pricing");
                });

            modelBuilder.Entity("MyFrete.Modules.Requests.Domain.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_professional_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("destination_address");

                    b.Property<Point>("DestinationPoint")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("destination_point");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_meters");

                    b.Property<string>("DistanceSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("distance_source");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_price");

                    b.Property<int>("EstimatedWeightGrams")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_weight_grams");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origin_address");

                    b.Property<Point>("OriginPoint")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("origin_point");

                    b.Property<Guid>("PricingRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_rule_id");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transport_request");

                    b.HasIndex("OriginPoint")
                        .HasDatabaseName("ix_transport_request_origin_point");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OriginPoint"), "gist");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_transport_request_status");

                    b.HasIndex("ClientId", "CreatedAt")
                        .HasDatabaseName("ix_transport_request_client_id_created_at");

                    b.ToTable("transport_request", "requests");
                });

            modelBuilder.Entity("MyFrete.Modules.Trips.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgreedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("agreed_amount");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ClientRespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_responded_at");

                    b.Property<string>("ClientResponse")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("client_response");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<bool>("PaymentSettledOutsideApp")
                        .HasColumnType("boolean")
                        .HasColumnName("payment_settled_outside_app");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("VerificationNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_notified_at");

                    b.HasKey("Id")
                        .HasName("pk_trip");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_request_id");

                    b.HasIndex("ClientId", "CreatedAt")
                        .HasDatabaseName("ix_trip_client_id_created_at");

                    b.HasIndex("ProfessionalId", "Status")
                        .HasDatabaseName("ix_trip_professional_id_status");

                    b.ToTable("trip", "trips");
                });
#pragma warning restore 612, 618
        }
    }
}
