/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria conta (cliente e/ou profissional) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e retorna tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotaciona o refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da conta autenticada */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra token de push do dispositivo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        platform: "ios" | "android";
                        token: string;
                    };
                };
            };
            responses: {
                /** @description registrado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/professionals/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza carga máxima e disponibilidade imediata */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        maxLoadKg?: number;
                        immediateAvailability?: boolean;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfessionalProfile"];
                    };
                };
                /** @description não pode ficar disponível com transporte ativo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/professionals/me/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza a localização atual (enquanto disponível) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lat: number;
                        lng: number;
                    };
                };
            };
            responses: {
                /** @description registrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/professionals/me/schedule-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datas em que o profissional está disponível para agendamento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        /** Substitui a lista de datas disponíveis */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": string[];
                };
            };
            responses: {
                /** @description atualizado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimativa de preço sem criar requisição (FR-008/010) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EstimateRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceEstimate"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de requisições do cliente autenticado (FR-029) */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransportRequestPage"];
                    };
                };
            };
        };
        put?: never;
        /** Cria e confirma uma requisição imediata (FR-006, inicia matching) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRequest"];
                };
            };
            responses: {
                /** @description criada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransportRequest"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe e status atual da requisição (FR-017) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransportRequest"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cliente cancela a requisição (FR-026) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description cancelada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransportRequest"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/schedule-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resposta do cliente à oferta de agendamento (FR-018/019/023) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["RequestId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "schedule" | "decline";
                        /**
                         * Format: date
                         * @description obrigatório se decision=schedule
                         */
                        scheduledDate?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransportRequest"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oferta pendente para o profissional autenticado (imediata ou de agendamento) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Offer"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profissional aceita a oferta (FR-014/015/016/022) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: components["parameters"]["OfferId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description aceita */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
                /** @description janela expirada, já preenchida por outro, ou profissional inelegível */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profissional recusa a oferta (passa ao próximo) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["OfferId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description recusada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do transporte */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}/agreed-amount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ajusta o valor combinado antes da conclusão (FR-025) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/trips/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profissional marca o transporte como entregue (FR-025b) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description entregue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}/client-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cliente confirma ou contesta a entrega (FR-025c) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        response: "confirm" | "dispute";
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cliente ou profissional cancela antes do início (FR-027) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description cancelado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de transportes do profissional autenticado (FR-029) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TripPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privacy/data-subject-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicita acesso, correção ou exclusão dos próprios dados (FR-030) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        kind: "access" | "rectification" | "deletion";
                        details?: string;
                    };
                };
            };
            responses: {
                /** @description registrada */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details */
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            errors?: {
                [key: string]: string[];
            };
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            /** @description E.164 */
            phone: string;
            password: string;
            roles: ("client" | "professional")[];
            /** @description obrigatório se roles inclui professional */
            maxLoadKg?: number;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthTokens: {
            accessToken?: string;
            refreshToken?: string;
            expiresInSeconds?: number;
        };
        Me: {
            /** Format: uuid */
            id?: string;
            name?: string;
            email?: string;
            phone?: string;
            roles?: string[];
            professional?: components["schemas"]["ProfessionalProfile"];
        };
        ProfessionalProfile: {
            maxLoadKg?: number;
            immediateAvailability?: boolean;
            /** @enum {string} */
            verificationStatus?: "nao_verificado" | "em_analise" | "verificado" | "rejeitado";
            /** Format: date-time */
            lastLocationAt?: string | null;
        };
        GeoPoint: {
            lat: number;
            lng: number;
        };
        Address: {
            text: string;
            point?: components["schemas"]["GeoPoint"];
        };
        EstimateRequest: {
            origin: components["schemas"]["Address"];
            destination: components["schemas"]["Address"];
            estimatedWeightKg: number;
        };
        PriceEstimate: {
            amount?: number;
            /** @example BRL */
            currency?: string;
            distanceKm?: number;
            /** @enum {string} */
            distanceSource?: "routed" | "geodesic_fallback";
            /** @example true */
            isEstimate?: boolean;
        };
        CreateRequest: components["schemas"]["EstimateRequest"] & {
            items: {
                description: string;
                /** @default 1 */
                quantity: number;
            }[];
        };
        TransportRequest: {
            /** Format: uuid */
            id?: string;
            /**
             * @description status consolidado da requisição; `completed` é atingido quando o Trip chega a `entregue` (uma contestação posterior fica em Trip.status = contestada) — ver data-model.md
             * @enum {string}
             */
            status?: "draft" | "searching" | "hired" | "awaiting_schedule_decision" | "scheduled_searching" | "scheduled" | "completed" | "unfulfilled" | "cancelled";
            /**
             * @description status do Trip quando já houver vínculo
             * @enum {string|null}
             */
            tripStatus?: "contratada" | "em_andamento" | "entregue" | "confirmada" | "contestada" | "cancelada" | null;
            /** @enum {string} */
            kind?: "immediate" | "scheduled";
            /** Format: date */
            scheduledDate?: string | null;
            estimate?: components["schemas"]["PriceEstimate"];
            items?: Record<string, never>[];
            originAddress?: string;
            destinationAddress?: string;
            assignedProfessional?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                verificationStatus?: string;
            } | null;
            /** Format: uuid */
            tripId?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        TransportRequestPage: {
            items?: components["schemas"]["TransportRequest"][];
            page?: number;
            total?: number;
        };
        Offer: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            requestId?: string;
            /** @enum {string} */
            type?: "immediate" | "scheduled";
            /** Format: date-time */
            respondBy?: string | null;
            /** Format: date */
            scheduledDate?: string | null;
            summary?: {
                originAddress?: string;
                destinationAddress?: string;
                distanceKm?: number;
                estimatedWeightKg?: number;
                estimatedAmount?: number;
            };
        };
        Trip: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            requestId?: string;
            /** @enum {string} */
            status?: "contratada" | "em_andamento" | "entregue" | "confirmada" | "contestada" | "cancelada";
            agreedAmount?: number;
            /** @example BRL */
            currency?: string;
            /** Format: date-time */
            deliveredAt?: string | null;
            /** @enum {string|null} */
            clientResponse?: "confirmada" | "contestada" | null;
            paymentSettledOutsideApp?: boolean;
            counterparty?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                /** @description revelado só após vínculo (FR-031) */
                phone?: string;
            };
        };
        TripPage: {
            items?: components["schemas"]["Trip"][];
            page?: number;
            total?: number;
        };
    };
    responses: {
        /** @description não autenticado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description não encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description conflito de estado */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description entrada inválida */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        RequestId: string;
        OfferId: string;
        TripId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
